// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KPPpUNXU2SPX6hFCO7Qx_o16Fl3ozfA',
    appId: '1:367614407339:web:c1a706485d33243359bdee',
    messagingSenderId: '367614407339',
    projectId: 'food-ecom-e4584',
    authDomain: 'food-ecom-e4584.firebaseapp.com',
    storageBucket: 'food-ecom-e4584.appspot.com',
    measurementId: 'G-EEP057FD47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgBV6oy9gMrRH-KJZSkj5YTvfG3GkNDg0',
    appId: '1:367614407339:android:7541a82c2f12e01559bdee',
    messagingSenderId: '367614407339',
    projectId: 'food-ecom-e4584',
    storageBucket: 'food-ecom-e4584.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_o8C_NfCZMu2hodBjkDeu5jwpIT8nbTc',
    appId: '1:367614407339:ios:99543e9c8288a53459bdee',
    messagingSenderId: '367614407339',
    projectId: 'food-ecom-e4584',
    storageBucket: 'food-ecom-e4584.appspot.com',
    iosBundleId: 'com.example.foodEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_o8C_NfCZMu2hodBjkDeu5jwpIT8nbTc',
    appId: '1:367614407339:ios:f326d90d1325cb0959bdee',
    messagingSenderId: '367614407339',
    projectId: 'food-ecom-e4584',
    storageBucket: 'food-ecom-e4584.appspot.com',
    iosBundleId: 'com.example.foodEcom.RunnerTests',
  );
}
